{% set version = "1.6.0" %}
{% set name = "JPype1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 2d46b2a14f8f0e6f17d8aa22b4fc3a64b2790851ebf1409ad79a37c698fd6e9a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - openjdk
  host:
    - python
    - pip
    - setuptools
    # - setupext unavailable

  run:
    - python
    - typing_extensions  # [py<38]
    - packaging

test:
  imports:
    - jpype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python to Java bridge.
  description: A Python to Java bridge.
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
