{% set version = "0.7.2" %}
{% set name = "JPype1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb31c7b89b90f0276c19d525b3d2df908e06d3a5066a2df839cc824b73943b6e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - jpype

about:
  home: https://github.com/jpype-project/jpype
  license: Apache
  license_file: LICENSE
  summary: 'A Python to Java bridge.'
  description: 'A Python to Java bridge.'
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
