{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpype-project/jpype/archive/refs/tags/v{{ version }}.zip
  sha256: 7bd0b3940cebf448dd94a9a6ec3a2f17a9b349eaa55312c9b737eb4ce269b437

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    # - setupext unavailable
  run:
    - python
    - typing_extensions  # [py<38]
    - packaging

test:
  imports:
    - jpype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python to Java bridge.
  description: A Python to Java bridge.
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
